######################################################################
#
# File name : tb_epp_basic_simulate.do
# Created on: Thu Mar 28 11:22:53 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_epp_basic xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_epp_basic_wave.do}

view wave
view structure
view signals

do {tb_epp_basic.udo}

run 1000ns
