######################################################################
#
# File name : tb_epp_basic_compile.do
# Created on: Thu Mar 28 11:22:52 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -work xil_defaultlib  "+incdir+../../../../a7_epp_1080p.gen/sources_1/ip/clk_wiz_0" \
"../../../../a7_epp_1080p.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../a7_epp_1080p.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../../epp_basic.v" \
"../../../../tb_epp_basic.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

